### PR TITLE
firefox support

### PR DESCRIPTION
**Pull request by 6a68**
Hey @gkovacs, I've naively applied the changes from the `firefox` branch on top of current master here. Some interventions work. Before I go digging in further, do you have any input on how you'd like the final patch to look?

### CODE REVIEW

**Comment by 6a68** [comment]
I'll just continue on my own.

**Comment by gkovacs** [comment]
Hey, thanks for the PR! I looked at the patch and it looks fine. Let me know when you want to merge it.

**Comment by 6a68** [comment]
@gkovacs oh, great! I wasn't sure if any of the changes might break the chrome version. Land away :+1:

**Comment by 6a68** [comment]
@gkovacs hey, let's land this when you get a spare minute!

also, where's a good place to work out steps for publishing on addons.mozilla.org once this lands?

I figure I'll just file bugs to document which interventions are busted on firefox. I might be able to nerd snipe some other mozilla folks into contributing fixes 🙃

**Comment by 6a68** [comment]
ah, this seems to be beachballing nightly on my mac. let's wait to land it till I find the bug.

**Comment by lamyergeier** [comment]
Is it available for Firefox?

**Pull request closed without merging**
